version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ted-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ted_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - ted-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ted-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/ted_db?authSource=admin
      - RUGS_BACKEND_URL=https://backend.rugs.fun?frontend-version=1.0
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
      - MAX_RECONNECT_ATTEMPTS=10
      - RECONNECT_DELAY=1000
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - mongodb
    networks:
      - ted-network
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ted-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
      - WDS_SOCKET_PORT=3000
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ted-network
    stdin_open: true
    tty: true

volumes:
  mongodb_data:

networks:
  ted-network:
    driver: bridge